/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RotasRouteImport } from './routes/rotas'
import { Route as PontoRouteImport } from './routes/ponto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuncionarioRouteImport } from './routes/funcionario'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as CargosRouteImport } from './routes/cargos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const RotasRoute = RotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoRoute = PontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionarioRoute = FuncionarioRouteImport.update({
  id: '/funcionario',
  path: '/funcionario',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const CargosRoute = CargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cargos': typeof CargosRoute
  '/financeiro': typeof FinanceiroRoute
  '/funcionario': typeof FuncionarioRoute
  '/login': typeof LoginRoute
  '/ponto': typeof PontoRoute
  '/rotas': typeof RotasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cargos': typeof CargosRoute
  '/financeiro': typeof FinanceiroRoute
  '/funcionario': typeof FuncionarioRoute
  '/login': typeof LoginRoute
  '/ponto': typeof PontoRoute
  '/rotas': typeof RotasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cargos': typeof CargosRoute
  '/financeiro': typeof FinanceiroRoute
  '/funcionario': typeof FuncionarioRoute
  '/login': typeof LoginRoute
  '/ponto': typeof PontoRoute
  '/rotas': typeof RotasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/cargos'
    | '/financeiro'
    | '/funcionario'
    | '/login'
    | '/ponto'
    | '/rotas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/cargos'
    | '/financeiro'
    | '/funcionario'
    | '/login'
    | '/ponto'
    | '/rotas'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/cargos'
    | '/financeiro'
    | '/funcionario'
    | '/login'
    | '/ponto'
    | '/rotas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CargosRoute: typeof CargosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FuncionarioRoute: typeof FuncionarioRoute
  LoginRoute: typeof LoginRoute
  PontoRoute: typeof PontoRoute
  RotasRoute: typeof RotasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rotas': {
      id: '/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof RotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto': {
      id: '/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof PontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionario': {
      id: '/funcionario'
      path: '/funcionario'
      fullPath: '/funcionario'
      preLoaderRoute: typeof FuncionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargos': {
      id: '/cargos'
      path: '/cargos'
      fullPath: '/cargos'
      preLoaderRoute: typeof CargosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CargosRoute: CargosRoute,
  FinanceiroRoute: FinanceiroRoute,
  FuncionarioRoute: FuncionarioRoute,
  LoginRoute: LoginRoute,
  PontoRoute: PontoRoute,
  RotasRoute: RotasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
